### PR TITLE
when the server receive a post request now it print the body on the log

### PR DESCRIPTION
**Pull request by bestbug456**
Hello,

I used your echo server, but for my test I need the server print the body on the log. I made this change and I would like to propose to you this small edit. Let me know!

Danilo

### CODE REVIEW

**Comment by jmalloc** [comment]
The body is [already echoed](https://github.com/jmalloc/echo-server/blob/master/cmd/echo-server/main.go#L112), regardless of the HTTP method - though it happens after all the headers are displayed.

**Comment by bestbug456** [comment]
Yeah is echoed to the client but not on the server logs, that's why I put it. If you still think is not useful I can close this pr, no problem :)

**Comment by TimJones** [comment]
I think this functionality is helpful when using something like docker-compose to run integrations tests, as it allows requests to be captured by logging rather than only the client.

I would maybe add a command flag  like `-log-echo` and then enable this functionality for all requests rather than just POST.

**Comment by jmalloc** [comment]
Sorry I missed this for so long!  I've wrapped the dumping logic inside a check for the `LOG_HTTP_BODY` environment variable -- so set that to any non-empty string and the bodies will be logged :)

**Pull request merged**
